version: '3'
services:
  db:
    build:
      context: ./db
    ports:
        - "3306:3306"
    healthcheck:
      test: "exit 0"
      interval: 2s
      timeout: 2s
      retries: 5

  api:
    build:
      context: ./api  
    ports:
        - "8080:8080"
    depends_on:
        db:
          condition: service_healthy


